
demo:
  storage:
    table:
      endpoint: ${embedded.azurite.table-endpoint}

spring:
  cloud:
    azure:
      storage:
        blob:
          account-name: ${embedded.azurite.account-name}
          endpoint: ${embedded.azurite.blob-endpoint}
          account-key: ${embedded.azurite.account-key}
        queue:
          account-name: ${embedded.azurite.account-name}
          endpoint: ${embedded.azurite.queue-endpoint}
          account-key: ${embedded.azurite.account-key}
          queue-name: testqueue

